openapi: 3.0.1
info:
  title: sretest2
  version: v1
servers:
  - url: /
security:
  - default: []
paths:
  /*:
    get:
      summary: ""
      description: ""
      responses:
        "200":
          description: OK
      security:
        - default:
            - srescope
            - srescopeone
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
          - oauth2
        optional: false
    put:
      summary: ""
      description: ""
      responses:
        "200":
          description: OK
      security:
        - default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
          - oauth2
        optional: false
    post:
      summary: ""
      description: ""
      responses:
        "200":
          description: OK
      security:
        - default:
            - srescope
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
          - oauth2
        optional: false
    delete:
      responses:
        "200":
          description: OK
      security:
        - default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
          - oauth2
        optional: false
    patch:
      summary: ""
      description: ""
      responses:
        "200":
          description: OK
      security:
        - default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
          - oauth2
        optional: false
components:
  securitySchemes:
    default:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://test.com
          scopes:
            srescopetwo: srescopetwo description
            srescope: srescope
            srescopeone: srescopeone description
          x-scopes-bindings:
            srescope: admin
            srescopetwo: admin
            srescopeone: admin
x-wso2-auth-header: Authorization
x-wso2-cors:
  corsConfigurationEnabled: false
  accessControlAllowOrigins:
    - "*"
  accessControlAllowCredentials: false
  accessControlAllowHeaders:
    - authorization
    - Access-Control-Allow-Origin
    - Content-Type
    - SOAPAction
    - apikey
    - Internal-Key
  accessControlAllowMethods:
    - GET
    - PUT
    - POST
    - DELETE
    - PATCH
    - OPTIONS
x-wso2-production-endpoints:
  urls:
    - https://run.mocky.io/v3/a136ec16-c5c5-4145-abef-9e821f23768b
  type: http
x-wso2-sandbox-endpoints:
  urls:
    - https://run.mocky.io/v3/a136ec16-c5c5-4145-abef-9e821f23768b
  type: http
x-wso2-basePath: /sretest2/v1
x-wso2-transports:
  - http
  - https
x-wso2-response-cache:
  enabled: false
  cacheTimeoutInSeconds: 300
